################### ------------------------------
## REQUISIÇÕES DE RESTAURANTE

###
//TODOS OS CUPONS DE UM RESTAURANTE 
GET http://localhost:3000/promotion/restaurants/Mequi

###
//TODOS OS CUPONS DE TODOS OS RESTAURANTES
GET http://localhost:3000/promotion/restaurants

###
//INSERINDO UM CUPON A UM RESTAURANTE
POST http://localhost:3000/promotion/restaurants/Mequi
Content-Type: application/json

{
    "name": "QUARTEIRAO",
    "adm": false,
    "minValue": 15,
    "product": "Big Méqui",
    "discount": 0.1,
    "status": "Inativo"
}

// ATUALIZA CUPOM DO RESTAURANTE
###
PUT http://localhost:3000/promotion/restaurants/Mequi/2BIGMEQUIPOR5
Content-Type: application/json

{
    "name":"2BIGMEQUIPOR9",
    "discount" : 0.6
}


####################### ---------------------------------
# REQUISIÇÕES DE ADMIN

###
//MOSTRA TODOS OS CUPONS DE ADMIN 
GET  http://localhost:3000/promotion/admin

###
GET  http://localhost:3000/promotion/admin/login/578dbdea

###
//ADICIONA UM CUPOM DO ADMIN
POST http://localhost:3000/promotion/admin
Content-Type: application/json

{
    "name": "50off",
    "adm": true,
    "minValue" : 10000,
    "discount": 0.5,
    "status": "Inativo"
}


### 
//ATUALIZA UM CUPOM DO ADMIN
PUT  http://localhost:3000/promotion/admin/50%OFF
Content-Type: application/json

{
    "name":"20%OFF",
    "discount":0.2
}

//REMOVE UM CUPON DO ADM
###
DELETE http://localhost:3000/promotion/admin/50%OFF


####################### ---------------------------------
# REQUISIÇÕES DE USUÁRIO

# RETORNA TODOS OS PEDIDOS DE UM USUÁRIO
###
GET http://localhost:3000/user/11a84677/orders

# TENTA ADICIONAR CUPOM QUE NÃO ATINGE O VALOR MÍNIMO AO PEDIDO
###
POST http://localhost:3000/user/11a84677/order
Content-Type: application/json

{
    "couponName" : "2BIGMEQUIPOR1",
    "order" : 
    {
        "products": [
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Cheddar Méquimelt",
                "price": 12
            }
        ],
        "amount": 42,
        "restaurant": "Mequi"
    }
}


# TENTA ADICIONAR CUPOM NÃO EXISTENTE AO PEDIDO
###
POST http://localhost:3000/user/11a84677/order
Content-Type: application/json

{
    "couponName" : "mileto",
    "order" : 
    {
        "products": [
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Cheddar Méquimelt",
                "price": 12
            }
        ],
        "amount": 27,
        "restaurant": "Mequi"
    }
}

# REMOVE CUPOM DO PEDIDO
###
DELETE http://localhost:3000/user/11a84677/order
Content-Type: application/json

{
    "couponName" : "2BIGMEQUIPOR9",
    "order" : 
    {
        "products": [
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Cheddar Méquimelt",
                "price": 12
            }
        ],
        "amount": 16,
        "restaurant": "Mequi"
    }
}

###
# ADICIONA CUPOM AO PEDIDO
POST http://localhost:3000/user/11a84677/order
Content-Type: application/json

{
    "couponName" : "2BIGMEQUIPOR9",
    "order" : 
    {
        "products": [
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Big Méqui",
                "price": 15
            },
            {
                "name": "Cheddar Méquimelt",
                "price": 12
            }
        ],
        "amount": 42,
        "restaurant": "Mequi"
    }
}

# ADICIONA UM PEDIDO AO ARRAY DE PEDIDOS DO USUÁRIO
###
POST http://localhost:3000/user/11a84677/orders
Content-Type: application/json

{
    "products": [
        {
            "name": "Big Méqui",
            "price": 15
        },
        {
            "name": "Big Méqui",
            "price": 15
        },
        {
            "name": "Cheddar Méquimelt",
            "price": 12
        }
    ],
    "amount": 16.8,
    "restaurant": "Mequi",
    "coupon": {
        "id": "388ac565",
        "name": "2BIGMEQUIPOR9",
        "adm": false,
        "minValue": 15,
        "product": "Big Méqui",
        "discount": 0.6,
        "status": "Ativo",
        "begin": "21:00-02/04/2022",
        "end": "21:00-06/04/2022"
    }
}

###
POST http://localhost:3000/user/11a84677/orders
Content-Type: application/json

{
    "products": [
        {
            "name": "Big Méqui",
            "price": 15
        }
    ],
    "amount": 14,
    "restaurant": "Mequi",
    "coupon": {
        "id": "388ac565",
        "name": "2BIGMEQUIPOR9",
        "adm": false,
        "minValue": 15,
        "product": "Big Méqui",
        "discount": 0.6,
        "status": "Ativo",
        "begin": "21:00-02/04/2022",
        "end": "21:00-06/04/2022"
    }
}

